apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "privileges-raise"
  annotations:
    description: "Detects privileges raising operations"
spec:
  kprobes:
  - call: "create_user_ns"
    syscall: false
    message: "Process created a user namespace"
    args:
    - index: 0
      type: "nop" # No need for argument as this targets unprivileged anyway.
    selectors:
    - matchCapabilities:
      - type: Effective
        operator: NotIn
        values:
        - "CAP_SYS_ADMIN"
  - call: "__sys_setuid"
    message: "Operation setuid invoked"
    syscall: false
    args:
    - index: 0
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "NotEqual"
        values:
        - "0"
      matchActions:
      - action: Post
  - call: "__sys_setgid"
    message: "Operation setgid invoked"
    syscall: false
    args:
    - index: 0
      type: "int"
    selectors:
    - matchArgs:
      - index: 0
        operator: "NotEqual"
        values:
        - "0"
      matchActions:
      - action: Post
  # - call: "__sys_setreuid"
  #   message: "Privileged operation setuid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  #   - matchArgs:
  #     - index: 1
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  # - call: "__sys_setregid"
  #   message: "Privileged operation setgid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  #   - matchArgs:
  #     - index: 1
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  # - call: "__sys_setresuid"
  #   message: "Privileged operation setuid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   - index: 2
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 1 # We care about the effective user id to reduce noise
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  #   - matchArgs:
  #     - index: 2
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  # - call: "__sys_setresgid"
  #   message: "Privileged operation setgid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   - index: 1
  #     type: "int"
  #   - index: 2
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 1 # We care about the effective group id to reduce noise
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  #   - matchArgs:
  #     - index: 2
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  # - call: "__sys_setfsuid"
  #   message: "Privileged operation setuid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min
  # - call: "__sys_setfsgid"
  #   message: "Privileged operation setgid to root"
  #   syscall: false
  #   args:
  #   - index: 0
  #     type: "int"
  #   selectors:
  #   - matchArgs:
  #     - index: 0
  #       operator: "Equal"
  #       values:
  #       - "0"
  #     matchActions:
  #     - action: Post
  #       rateLimit: "1m"  # Rate limit messages to 1min


