apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints", "replicationcontrollers", "persistentvolumeclaims", "events", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["daemonsets", "deployments", "replicasets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-binding
subjects:
  - kind: ServiceAccount
    name: otel-collector
    namespace: default
roleRef:
  kind: ClusterRole
  name: otel-collector-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    extensions:
      basicauth/client:
        client_auth:
          username: admin
          password: admin
    receivers:
      filelog:
        include: ["/var/run/cilium/tetragon/tetragon.log"]
        start_at: end
        operators:
          - type: json_parser
            timestamp:
              parse_from: attributes.time
              layout: '%Y-%m-%d %H:%M:%S'
          - type: remove
            field: attributes.time
          - type: move
            from: attributes.msg
            to: body


    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      opensearch/logs:
        logs_index: "tetragon_logs"
        http:
          endpoint: "${OPENSEARCH_ENDPOINT}"
          auth:
            authenticator: basicauth/client
          tls:
            insecure_skip_verify: true
            ca_file: ""
            ca_pem: ""

    service:
      extensions: [basicauth/client]
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [logging, opensearch/logs]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: default
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      serviceAccountName: otel-collector
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        args: ["--config=/etc/otel-config/otel-collector-config.yaml"]
        env:
          - name: OPENSEARCH_ENDPOINT
            value: "https://10.160.3.185:30020"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel-config
        - name: tetragon-logs
          mountPath: /var/run/cilium/tetragon
        securityContext:
          privileged: true
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
      - name: tetragon-logs
        hostPath:
          path: /var/run/cilium/tetragon
          type: DirectoryOrCreate
